Add What's new file for iOS 6.0
mozilla-l10n/appstores pull request #78
Opened 2016-12-21 04:27 UTC by Delphine

2016-12-21 06:13 UTC, flodolo requested changes

2016-12-21 06:13 UTC, flodolo commented on en-US/whatsnew/whatsnew_ios_6_0.lang
> +;Automatically open web links in Firefox from mail apps such as Outlook, Airmail, Mail.Ru, myMail and Spark.  Also, make one of these mail services your default mail app when sending emails from Fire
We need to fix the double space in this string before 'Also'. Running lang_update again will fix all other locales, but you'll have to manually fix German (I see you've copied the strings 👍)

2016-12-22 05:35 UTC, Delphine reviewed
Fixed the double space before "Also"

2016-12-22 05:51 UTC, flodolo approved these changes

2016-12-22 05:52 UTC, flodolo commented
There was a small issue with this one: you've updated the en-US file, but forgot to run `lang_update` to export the string to all locales. Always remember to check the Errors page when you're done, since this kind of issue is reported there.

2016-12-22 05:53 UTC, merged